name: Build and Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: jerghy/Fair
          ref: main
          path: fair_online/fair_online
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.0'
      - name: Get dependencies
        run: flutter pub get
      - name: Build web
        run: flutter build web
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: build/web
